# .github/workflows/deploy.yml
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Astro
        run: npm install -g @netlify/astro-cli
      - name: Build Astro Site
        run: astro build
      - name: Deploy to S3
        run: |
          aws s3 sync dist s3://${BUCKET_NAME}
